import os from "node:os";
import path from "node:path";
import fs from "fs-extra";
import type { InstallOutcome } from "../types.js";
import { backupIfExists } from "../backup.js";

/**
 * Generate a Gradle init script that, after every `assembleDebug` /
 * `assembleRelease` / `bundleRelease` task in any project, locates the
 * produced APK/AAB and pipes it through the Build Delivery MCP CLI.
 *
 * The script intentionally exits early when:
 *   - The CLI is not installed (no global `build-delivery-mcp` binary)
 *   - BUILD_DELIVERY_DISABLE=1 is set in the env (CI escape hatch)
 *
 * Idempotent: re-running re-creates the same script, with a backup of
 * any prior version written alongside.
 */
export function gradleInitScript(deliverCommand: string): string {
  const safeCmd = deliverCommand.replace(/'/g, "\\'");
  return `// Auto-generated by build-delivery-mcp install-agents.
// Drops every Android build artifact into the Build Delivery pipeline
// (Telegram / WhatsApp / Slack / Discord / Email / Teams) without
// touching the original file.

allprojects {
    afterEvaluate { project ->
        def assembleTasks = project.tasks.matching { it.name.startsWith('assemble') || it.name.startsWith('bundle') }
        assembleTasks.all { task ->
            task.doLast {
                if (System.getenv('BUILD_DELIVERY_DISABLE') == '1') return
                def outputs = []
                project.fileTree(project.buildDir).matching {
                    include '**/*.apk'
                    include '**/*.aab'
                }.each { f -> outputs << f }
                outputs.each { artifact ->
                    try {
                        def deliver = '${safeCmd}'.split(/\\s+/)
                        def cmd = deliver + [artifact.absolutePath]
                        println "[build-delivery-mcp] dispatching \${artifact.name}"
                        def proc = new ProcessBuilder(cmd as List).redirectErrorStream(true).start()
                        proc.inputStream.eachLine { line -> println "[build-delivery-mcp] \${line}" }
                        proc.waitFor()
                    } catch (Exception e) {
                        println "[build-delivery-mcp] skipped (\${e.message})"
                    }
                }
            }
        }
    }
}
`;
}

export interface GradleInstallOptions {
  readonly deliverCommand: string;
  readonly dryRun?: boolean;
}

export async function installGradleHook(
  options: GradleInstallOptions,
): Promise<InstallOutcome> {
  const initDir = path.join(os.homedir(), ".gradle", "init.d");
  const scriptPath = path.join(initDir, "build-delivery-mcp.gradle");
  const next = gradleInitScript(options.deliverCommand);

  let existing = "";
  let exists = false;
  if (await fs.pathExists(scriptPath)) {
    exists = true;
    existing = await fs.readFile(scriptPath, "utf8");
  }

  if (existing === next) {
    return { agentId: "claude-desktop", path: scriptPath, status: "unchanged" };
  }

  if (options.dryRun) {
    return {
      agentId: "claude-desktop",
      path: scriptPath,
      status: exists ? "updated" : "added",
      message: "dry run — no file written",
    };
  }

  const backup = exists ? await backupIfExists(scriptPath) : null;
  await fs.ensureDir(initDir);
  await fs.writeFile(scriptPath, next, "utf8");
  return {
    agentId: "claude-desktop",
    path: scriptPath,
    status: exists ? "updated" : "added",
    backupPath: backup ?? undefined,
  };
}
