import path from "node:path";
import fs from "fs-extra";
import type { InstallOutcome } from "../types.js";

/**
 * Xcode does not have a global "init script" equivalent, so we write a
 * snippet the user pastes into a Run Script Build Phase (or an Archive
 * post-action). Running this command directly during installation is
 * intentionally NOT done — the user owns their .xcodeproj.
 */
export function xcodePostBuildScript(deliverCommand: string): string {
  const safeCmd = deliverCommand.replace(/'/g, "'\\''");
  return `# Auto-generated by build-delivery-mcp install-agents.
# Paste this into a Run Script Build Phase (preferably the last phase
# of your Archive scheme's post-actions). Set the shell to /bin/bash.
#
# It locates the IPA produced by the current archive and feeds it to the
# Build Delivery MCP CLI. Set BUILD_DELIVERY_DISABLE=1 to skip.

set -euo pipefail

if [[ "\${BUILD_DELIVERY_DISABLE:-0}" = "1" ]]; then
  echo "[build-delivery-mcp] disabled via env"
  exit 0
fi

# Try common Xcode env vars, then fall back to scanning the archive path.
IPA_PATH="\${ARCHIVE_PATH:-}/Products/Applications/\${PRODUCT_NAME:-}.app"
if [[ -z "\${ARCHIVE_PATH:-}" || ! -d "$IPA_PATH" ]]; then
  IPA_PATH=\$(find "\${BUILT_PRODUCTS_DIR:-.}" -name '*.ipa' -type f -print -quit 2>/dev/null || true)
fi

if [[ -z "$IPA_PATH" || ! -e "$IPA_PATH" ]]; then
  echo "[build-delivery-mcp] no IPA found; skipping"
  exit 0
fi

echo "[build-delivery-mcp] dispatching $IPA_PATH"
${safeCmd} "$IPA_PATH" || echo "[build-delivery-mcp] delivery failed (continuing)"
`;
}

export interface XcodeInstallOptions {
  readonly deliverCommand: string;
  readonly outputPath: string;
  readonly dryRun?: boolean;
}

export async function writeXcodeSnippet(
  options: XcodeInstallOptions,
): Promise<InstallOutcome> {
  const next = xcodePostBuildScript(options.deliverCommand);
  let existing = "";
  let exists = false;
  if (await fs.pathExists(options.outputPath)) {
    exists = true;
    existing = await fs.readFile(options.outputPath, "utf8");
  }
  if (existing === next) {
    return { agentId: "claude-desktop", path: options.outputPath, status: "unchanged" };
  }
  if (options.dryRun) {
    return {
      agentId: "claude-desktop",
      path: options.outputPath,
      status: exists ? "updated" : "added",
      message: "dry run — no file written",
    };
  }
  await fs.ensureDir(path.dirname(options.outputPath));
  await fs.writeFile(options.outputPath, next, "utf8");
  return {
    agentId: "claude-desktop",
    path: options.outputPath,
    status: exists ? "updated" : "added",
  };
}
