import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { ConfigStore } from "./config/store.js";
import { BuildHistory } from "./history/buildHistory.js";
import { DeliveryPipeline } from "./pipeline.js";
import { BuildWatcher } from "./watcher/fileWatcher.js";
import { TokenStore } from "./install-tracking/tokenStore.js";
import { InstallServer } from "./install-tracking/server.js";
import { dispatchTool, toolDefinitions } from "./tools/index.js";
import type { TrackingContext } from "./tools/handlers.js";
import { logger } from "./utils/logger.js";

export async function createServer(): Promise<{
  start: () => Promise<void>;
  stop: () => Promise<void>;
}> {
  const config = await ConfigStore.load();
  const history = new BuildHistory(100);
  const pipeline = new DeliveryPipeline(config, history);

  const tracking: TrackingContext = {
    installServer: null,
    tokenStore: null,
    onChange: (store) => {
      pipeline.setTokenStore(store);
    },
  };

  // If the active profile already has tracking enabled, auto-start it so
  // links generated by the pipeline immediately resolve.
  const { profile } = config.resolveProfile();
  if (profile.intel.tracking.enabled) {
    try {
      const store = new TokenStore(
        profile.intel.tracking.eventLogPath ?? "./.tracking/events.jsonl",
      );
      await store.init();
      const server = new InstallServer({
        port: profile.intel.tracking.port ?? 7331,
        store,
      });
      await server.start();
      tracking.installServer = server;
      tracking.tokenStore = store;
      pipeline.setTokenStore(store);
    } catch (err) {
      logger.warn(
        `Auto-start of install tracker failed: ${(err as Error).message}. ` +
          `You can start it manually with the start_install_server tool.`,
      );
    }
  }

  const watcher = new BuildWatcher({
    directories: profile.watcher.directories,
    extensions: profile.watcher.extensions,
    ignorePatterns: profile.watcher.ignorePatterns,
    stabilityThresholdMs: profile.watcher.stabilityThresholdMs,
    onBuild: async (filePath) => {
      await pipeline.process({ filePath });
    },
  });

  const server = new Server(
    { name: "build-delivery-mcp", version: "1.1.0" },
    { capabilities: { tools: {} } },
  );

  server.setRequestHandler(ListToolsRequestSchema, async () => ({
    tools: toolDefinitions,
  }));

  server.setRequestHandler(CallToolRequestSchema, async (request) => {
    const { name, arguments: args } = request.params;
    logger.debug(`Tool call: ${name}`);
    return dispatchTool(name, args ?? {}, {
      config,
      pipeline,
      history,
      watcher,
      tracking,
    });
  });

  const transport = new StdioServerTransport();

  return {
    async start() {
      await server.connect(transport);
      await watcher.start();
      logger.info("Build Delivery MCP server ready (stdio).");
    },
    async stop() {
      await watcher.stop();
      if (tracking.installServer) {
        await tracking.installServer.stop();
        tracking.installServer = null;
        tracking.tokenStore = null;
      }
      await pipeline.shutdown();
      await server.close();
      logger.info("Build Delivery MCP server stopped.");
    },
  };
}
